### ISSUE TITLE
CloudML image with cuDF and cuML

### ISSUE THREAD

**Issue by zronaghi** [rapidsai/cloud-ml-examples#60]
This Docker image will include RAPIDS libraries that will be needed for the examples in this repo, pruning the current CUDA 11 image

**Comment by zronaghi** [comment]
Cloud-ml and core images:

- 0.17-cloud-ml-cuda11 (17.1 GB)
- 0.18-cloud-ml-cuda11 (15.7 GB)
- 0.18-rapids-core-cuda11 (12 GB)
- 0.17-cloud-ml-cuda10.2 (14.1 GB)
- 0.18-cloud-ml-cuda10.2 (13 GB)
- 0.18-rapids-core-cuda10.2 (9.3 GB)

**Comment by miroenev** [comment]
Image | Pull | Size Uncompressed | Push | Size on ECR
-- | -- | -- | -- | --
rapidsai/rapidsai-cloud-ml:0.17-cuda11.0-base-ubuntu18.04-py3.8 | 9min 29sec | 17.2GB | 28min 40sec | 7923.1
rapidsai/rapidsai-cloud-ml:0.17-cuda10.2-base-ubuntu18.04-py3.8 | 9min 33sec | 14.1GB | 30min 49sec | 6333.86
rapidsai/rapidsai-cloud-ml:0.18-cuda11.0-base-ubuntu18.04-py3.8 | 12min 56sec | 15.7GB | 27min 8sec | 6895.85
rapidsai/rapidsai-cloud-ml:0.18-cuda10.2-base-ubuntu18.04-py3.8 | 7min 51sec | 13GB | 24min 26sec | 5682.91
rapidsai/rapidsai:cuda10.2-base-ubuntu18.04-py3.8 | 4min 51sec | 10.3GB | 22min 31sec | 4029.21

rapidsai/rapidsai-cloud-ml:0.18-cuda11.0-base-ubuntu18.04-py3.8 is still too large for the HPO demo, during the docker pull extraction phase the following error occurs since the docker default volume is full:

> failed to register layer: Error processing tar file(exit status 1): write /root/.cache/pip/http/4/3/7/e/7/437e787c9e19e9665f5a9dead6abeae241b406062ce908cccee5a73d: no space left on device

**Comment by zronaghi** [comment]
What size is the base+AWS dependencies that you've successfully run on SageMaker?

**Comment by miroenev** [comment]
The 0.16-cuda11.0-base-ubuntu18.04-py3.7 is an example of a passing cuda 11.0 based image. It is 4.16GB compressed, 10.7GB uncompressed, and 11.2GB with the additional packages (e.g. sagemaker-training-toolkit, flask, etc)


To reiterate the issue: when a new SageMaker notebook instance is launched the docker default volume (dev/xvda1) has 111GB total space of which 81% is occupied by the various conda kernels offered by SageMaker (see df output below).

!df -H
```
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        2.1G   66k  2.1G   1% /dev
tmpfs           2.1G     0  2.1G   0% /dev/shm
/dev/xvda1      111G   89G   23G  81% /
/dev/xvdf        27G  322M   25G   2% /home/ec2-user/SageMaker

```
!docker images
```
REPOSITORY                                                        TAG                                    IMAGE ID            CREATED             SIZE
561241433344.dkr.ecr.us-west-2.amazonaws.com/cloud-ml-sagemaker   0.16-cuda11.0-base-ubuntu18.04-py3.7   b3d1ab008d98        9 minutes ago       11.2GB
rapidsai/rapidsai                                                 0.16-cuda11.0-base-ubuntu18.04-py3.7   dcc78a483a78        4 months ago        10.7GB
```

**Comment by zronaghi** [comment]
cc @drobison00

**Comment by zronaghi** [comment]
Image size after pip/conda cache purge:

`0.18-cloud-ml-cuda11 (14.5 GB)`

**Comment by zronaghi** [comment]
After removing Ax, our images are 12.8GB for CUDA 11 and 10.4GB for CUDA 10

**Comment by zronaghi** [comment]
Closing this since we were able to reduce our image size, and will be smaller after rapids-core updates
